# Generated by Django 6.0.4 on 2026-06-27 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('deadline', models.DateTimeField()),
                ('priority_score', models.FloatField(default=0.0, help_text='Auto-calculated urgency score')),
                ('priority_tag', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=15)),
                ('category', models.CharField(blank=True, default='General', max_length=100)),
                ('estimated_hours', models.FloatField(default=1.0, help_text='Estimated hours to complete')),
                ('importance_weight', models.IntegerField(default=5, help_text='Importance from 1 (low) to 10 (critical)')),
                ('google_event_id', models.CharField(blank=True, help_text='Google Calendar event ID for sync', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['deadline', '-priority_score'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_text', models.TextField()),
                ('recommendation_type', models.CharField(choices=[('ranking', 'Priority Ranking'), ('time_block', 'Time Block Suggestion'), ('clash', 'Clash Warning'), ('general', 'General Suggestion')], default='general', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='tasks.task')),
            ],
            options={
                'db_table': 'ai_recommendations',
                'ordering': ['-generated_at'],
            },
        ),
    ]
